kind: Deployment
apiVersion: apps/v1
metadata:
  name: proxypool-server
  namespace: chainx-pre
  labels:
    app: proxypool-server
  annotations:
    deployment.kubernetes.io/revision: "3"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxypool-server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: proxypool-server
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: container-proxypool-server-pre
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:$BUILD_NUMBER
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-main
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: proxypool-server-env
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
            - name: proxy-log
              readOnly: false
              mountPath: /data/proxy
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      affinity: {}
      schedulerName: default-scheduler
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ""
          name: host-time
        - name: proxy-log
          emptyDir: {}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---
kind: Service
apiVersion: v1
metadata:
  name: proxypool-server-svc
  namespace: chainx-pre
  labels:
    app: proxypool-server-svc
spec:
  ports:
    - name: tcp-main
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: proxypool-server
status:
  loadBalancer: {}
