kind: Deployment
apiVersion: apps/v1
metadata:
  name: electrum-server
  namespace: pre
  labels:
    app: electrum-server
  annotations:
    deployment.kubernetes.io/revision: "3"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: electrum-server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: electrum-server
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: container-electrum-server-pre
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:$BUILD_NUMBER
          command: []
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          ports:
            - name: tcp-50001
              containerPort: 50001
              protocol: TCP
            - name: tcp-50002
              containerPort: 50002
              protocol: TCP
            - name: tcp-4224
              containerPort: 4224
              protocol: TCP
            - name: tcp-332
              containerPort: 8332
              protocol: TCP
          envFrom:
            - configMapRef:
                name: electrum-server-env
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      affinity: {}
      schedulerName: default-scheduler
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ""
          name: host-time
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---
kind: Service
apiVersion: v1
metadata:
  name: electrum-server-svc
  namespace: pre
  labels:
    app: electrum-server-svc
spec:
  ports:
    - name: tcp-50001
      protocol: TCP
      port: 50001
      targetPort: 50001
    - name: tcp-50002
      protocol: TCP
      port: 50002
      targetPort: 50002
    - name: tcp-4224
      protocol: TCP
      port: 4224
      targetPort: 4224
    - name: tcp-8332
      protocol: TCP
      port: 8332
      targetPort: 8332
  selector:
    app: electrum-server
status:
  loadBalancer: {}
